# Generated by Django 3.2.14 on 2022-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0004_auto_20220719_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
