# Generated by Django 3.2.14 on 2022-07-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0005_auto_20220719_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='title',
        ),
    ]
