# Generated by Django 3.2.14 on 2022-07-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0007_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
