# Generated by Django 3.2.14 on 2022-07-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0008_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In process', 'Completed'), ('In process', 'In process'), ('In process', 'Not needed anymore')], default='In process', max_length=200),
        ),
    ]
