# Generated by Django 3.2.14 on 2022-07-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0010_remove_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
